### ISSUE TITLE
Feature-Extraction-1 needs to check for nulls

### ISSUE THREAD

**Issue by MH54321** [lukas/ml-class#19]
Hi!  Thanks for offering the NYC Training!  Running some of the scripts to make sure everything works and got some errors in feature-extraction-1.py because it didn't include the lines to remove nulls (and the 6th row of the sample data file has a null).
Thanks again!

# Remove the blank rows from the series:
target = target[pd.notnull(text)]
text = text[pd.notnull(text)]

**Comment by charlesfrye** [comment]
Actually, the purpose of `feature-extraction-1.py` is to [demonstrate the need for data pre-processing](https://youtu.be/qoyp8pBtCZ0?t=322). Good catch!
