### ISSUE TITLE
Missing scikit-learn dependency for linux/macosx?

### ISSUE THREAD

**Issue by viddo** [lukas/ml-class#32]
> ## [Check installation](https://github.com/lukas/ml-class/blob/31d046fa6bef40d9da2b6b95848d8351f83ee74d/README.md#check-installation)
> To make sure your installation works go to the directory where this file is and run
> ```
> python test-scikit.py
> ```

This currently fails, I figure `scikit-learn` might be missing in requirements.txt? It's mentioned in the windows installation, https://github.com/lukas/ml-class/blob/31d046fa6bef40d9da2b6b95848d8351f83ee74d/README.md#libraries

**Comment by lukas** [comment]
Thanks!  You're right.  I'll update requirements.txt.
