### ISSUE TITLE
wandb signup "Traceback (most recent call last)"

### ISSUE THREAD

**Issue by stevdodd** [lukas/ml-class#50]
`pip install -r requirements.txt`
`wandb signup`

how to solve traceback error help me , all log is given

> 

pip install -r requirements.txt
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tensorflow in /Users/survar/Library/Python/2.7/lib/python/site-packages (from -r requirements.txt (line 1)) (2.1.0)
Requirement already satisfied: keras in /Users/survar/Library/Python/2.7/lib/python/site-packages (from -r requirements.txt (line 2)) (2.3.1)
Requirement already satisfied: pandas in /Users/survar/Library/Python/2.7/lib/python/site-packages (from -r requirements.txt (line 3)) (0.24.2)
Requirement already satisfied: numpy in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from -r requirements.txt (line 4)) (1.8.0rc1)
Requirement already satisfied: pillow in /Users/survar/Library/Python/2.7/lib/python/site-packages (from -r requirements.txt (line 5)) (6.2.2)
Requirement already satisfied: wandb in /Users/survar/Library/Python/2.7/lib/python/site-packages (from -r requirements.txt (line 6)) (0.8.22)
Requirement already satisfied: h5py in /Users/survar/Library/Python/2.7/lib/python/site-packages (from -r requirements.txt (line 7)) (2.10.0)
Requirement already satisfied: opencv-python in /Users/survar/Library/Python/2.7/lib/python/site-packages (from -r requirements.txt (line 8)) (4.1.2.30)
Requirement already satisfied: scikit-learn in /Users/survar/Library/Python/2.7/lib/python/site-packages (from -r requirements.txt (line 9)) (0.20.4)
Requirement already satisfied: scikit-image in /Users/survar/Library/Python/2.7/lib/python/site-packages (from -r requirements.txt (line 10)) (0.14.5)
Requirement already satisfied: protobuf>=3.8.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from tensorflow->-r requirements.txt (line 1)) (3.11.2)
Requirement already satisfied: enum34>=1.1.6; python_version < "3.4" in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from tensorflow->-r requirements.txt (line 1)) (1.1.6)
Requirement already satisfied: absl-py>=0.7.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from tensorflow->-r requirements.txt (line 1)) (0.9.0)
Requirement already satisfied: functools32>=3.2.3; python_version < "3" in /Users/survar/Library/Python/2.7/lib/python/site-packages (from tensorflow->-r requirements.txt (line 1)) (3.2.3.post2)
Requirement already satisfied: gast==0.2.2 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from tensorflow->-r requirements.txt (line 1)) (0.2.2)
Requirement already satisfied: wheel; python_version < "3" in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from tensorflow->-r requirements.txt (line 1)) (0.33.1)
Requirement already satisfied: six>=1.12.0 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from tensorflow->-r requirements.txt (line 1)) (1.12.0)
Requirement already satisfied: termcolor>=1.1.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from tensorflow->-r requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: keras-applications>=1.0.8 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from tensorflow->-r requirements.txt (line 1)) (1.0.8)
Requirement already satisfied: astor>=0.6.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from tensorflow->-r requirements.txt (line 1)) (0.8.1)
Requirement already satisfied: mock>=2.0.0; python_version < "3" in /Users/survar/Library/Python/2.7/lib/python/site-packages (from tensorflow->-r requirements.txt (line 1)) (3.0.5)
Requirement already satisfied: google-pasta>=0.1.6 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from tensorflow->-r requirements.txt (line 1)) (0.1.8)
Requirement already satisfied: opt-einsum>=2.3.2 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from tensorflow->-r requirements.txt (line 1)) (2.3.2)
Requirement already satisfied: grpcio>=1.8.6 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from tensorflow->-r requirements.txt (line 1)) (1.26.0)
Requirement already satisfied: keras-preprocessing>=1.1.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from tensorflow->-r requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: tensorflow-estimator<2.2.0,>=2.1.0rc0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from tensorflow->-r requirements.txt (line 1)) (2.1.0)
Requirement already satisfied: scipy==1.2.2; python_version < "3" in /Users/survar/Library/Python/2.7/lib/python/site-packages (from tensorflow->-r requirements.txt (line 1)) (1.2.2)
Requirement already satisfied: tensorboard<2.2.0,>=2.1.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from tensorflow->-r requirements.txt (line 1)) (2.1.0)
Requirement already satisfied: wrapt>=1.11.1 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from tensorflow->-r requirements.txt (line 1)) (1.11.2)
Requirement already satisfied: backports.weakref>=1.0rc1; python_version < "3.4" in /Users/survar/Library/Python/2.7/lib/python/site-packages (from tensorflow->-r requirements.txt (line 1)) (1.0.post1)
Requirement already satisfied: pyyaml in /Users/survar/Library/Python/2.7/lib/python/site-packages (from keras->-r requirements.txt (line 2)) (5.3)
Requirement already satisfied: python-dateutil>=2.5.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from pandas->-r requirements.txt (line 3)) (2.8.1)
Requirement already satisfied: pytz>=2011k in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from pandas->-r requirements.txt (line 3)) (2013.7)
Requirement already satisfied: Click>=7.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from wandb->-r requirements.txt (line 6)) (7.0)
Requirement already satisfied: docker-pycreds>=0.4.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from wandb->-r requirements.txt (line 6)) (0.4.0)
Requirement already satisfied: subprocess32>=3.5.3 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from wandb->-r requirements.txt (line 6)) (3.5.4)
Requirement already satisfied: nvidia-ml-py3>=7.352.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from wandb->-r requirements.txt (line 6)) (7.352.0)
Requirement already satisfied: watchdog>=0.8.3 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from wandb->-r requirements.txt (line 6)) (0.10.0)
Requirement already satisfied: gql==0.2.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from wandb->-r requirements.txt (line 6)) (0.2.0)
Requirement already satisfied: psutil>=5.0.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from wandb->-r requirements.txt (line 6)) (5.6.7)
Requirement already satisfied: requests>=2.0.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from wandb->-r requirements.txt (line 6)) (2.22.0)
Requirement already satisfied: configparser>=3.8.1 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from wandb->-r requirements.txt (line 6)) (4.0.2)
Requirement already satisfied: GitPython>=1.0.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from wandb->-r requirements.txt (line 6)) (2.1.14)
Requirement already satisfied: sentry-sdk>=0.4.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from wandb->-r requirements.txt (line 6)) (0.14.1)
Requirement already satisfied: shortuuid>=0.5.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from wandb->-r requirements.txt (line 6)) (0.5.0)
Requirement already satisfied: matplotlib>=2.0.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from scikit-image->-r requirements.txt (line 10)) (2.2.4)
Requirement already satisfied: PyWavelets>=0.4.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from scikit-image->-r requirements.txt (line 10)) (1.0.3)
Requirement already satisfied: networkx>=1.8 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from scikit-image->-r requirements.txt (line 10)) (2.2)
Requirement already satisfied: cloudpickle>=0.2.1 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from scikit-image->-r requirements.txt (line 10)) (1.2.2)
Requirement already satisfied: setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from protobuf>=3.8.0->tensorflow->-r requirements.txt (line 1)) (41.0.1)
Requirement already satisfied: funcsigs>=1; python_version < "3.3" in /Users/survar/Library/Python/2.7/lib/python/site-packages (from mock>=2.0.0; python_version < "3"->tensorflow->-r requirements.txt (line 1)) (1.0.2)
Requirement already satisfied: futures>=2.2.0; python_version < "3.2" in /Users/survar/Library/Python/2.7/lib/python/site-packages (from grpcio>=1.8.6->tensorflow->-r requirements.txt (line 1)) (3.3.0)
Requirement already satisfied: werkzeug>=0.11.15 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow->-r requirements.txt (line 1)) (0.16.1)
Requirement already satisfied: google-auth<2,>=1.6.3 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow->-r requirements.txt (line 1)) (1.11.0)
Requirement already satisfied: markdown>=2.6.8 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow->-r requirements.txt (line 1)) (3.1.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from tensorboard<2.2.0,>=2.1.0->tensorflow->-r requirements.txt (line 1)) (0.4.1)
Requirement already satisfied: pyobjc-framework-Cocoa>=4.2.2; sys_platform == "darwin" in /Users/survar/Library/Python/2.7/lib/python/site-packages (from watchdog>=0.8.3->wandb->-r requirements.txt (line 6)) (5.3)
Requirement already satisfied: pathtools>=0.1.1 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from watchdog>=0.8.3->wandb->-r requirements.txt (line 6)) (0.1.2)
Requirement already satisfied: pyobjc-framework-FSEvents>=4.2.2; sys_platform == "darwin" in /Users/survar/Library/Python/2.7/lib/python/site-packages (from watchdog>=0.8.3->wandb->-r requirements.txt (line 6)) (5.3)
Requirement already satisfied: promise<3,>=2.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from gql==0.2.0->wandb->-r requirements.txt (line 6)) (2.3)
Requirement already satisfied: graphql-core<2,>=0.5.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from gql==0.2.0->wandb->-r requirements.txt (line 6)) (1.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from requests>=2.0.0->wandb->-r requirements.txt (line 6)) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from requests>=2.0.0->wandb->-r requirements.txt (line 6)) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from requests>=2.0.0->wandb->-r requirements.txt (line 6)) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from requests>=2.0.0->wandb->-r requirements.txt (line 6)) (2019.11.28)
Requirement already satisfied: gitdb2>=2.0.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from GitPython>=1.0.0->wandb->-r requirements.txt (line 6)) (2.0.6)
Requirement already satisfied: cycler>=0.10 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from matplotlib>=2.0.0->scikit-image->-r requirements.txt (line 10)) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from matplotlib>=2.0.0->scikit-image->-r requirements.txt (line 10)) (1.1.0)
Requirement already satisfied: backports.functools-lru-cache in /Users/survar/Library/Python/2.7/lib/python/site-packages (from matplotlib>=2.0.0->scikit-image->-r requirements.txt (line 10)) (1.6.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from matplotlib>=2.0.0->scikit-image->-r requirements.txt (line 10)) (2.0.1)
Requirement already satisfied: decorator>=4.3.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from networkx>=1.8->scikit-image->-r requirements.txt (line 10)) (4.4.1)
Requirement already satisfied: rsa<4.1,>=3.1.4 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow->-r requirements.txt (line 1)) (4.0)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow->-r requirements.txt (line 1)) (3.1.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow->-r requirements.txt (line 1)) (0.2.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.2.0,>=2.1.0->tensorflow->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: pyobjc-core>=5.3 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from pyobjc-framework-Cocoa>=4.2.2; sys_platform == "darwin"->watchdog>=0.8.3->wandb->-r requirements.txt (line 6)) (5.3)
Requirement already satisfied: typing>=3.6.4; python_version < "3.5" in /Users/survar/Library/Python/2.7/lib/python/site-packages (from promise<3,>=2.0->gql==0.2.0->wandb->-r requirements.txt (line 6)) (3.7.4.1)
Requirement already satisfied: smmap2>=2.0.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from gitdb2>=2.0.0->GitPython>=1.0.0->wandb->-r requirements.txt (line 6)) (2.0.5)
Requirement already satisfied: pyasn1>=0.1.3 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from rsa<4.1,>=3.1.4->google-auth<2,>=1.6.3->tensorboard<2.2.0,>=2.1.0->tensorflow->-r requirements.txt (line 1)) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /Users/survar/Library/Python/2.7/lib/python/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.2.0,>=2.1.0->tensorflow->-r requirements.txt (line 1)) (3.1.0)
$ cd videos
$ ls
autoencoder             cnn                     emotion-classifier      mlp                     text-classifier         transfer-learning
cifar-augmentation      cnn-audio               intro                   one-shot                text-gen                video-predict
cifar-learn-rate        cnn-text                lstm-classifier         seq2seq                 time-series
$ cd intro
$ ls
mlp.py                          perceptron-linear.py            perceptron-normalize.py         perceptron-single.py
mnist.png                       perceptron-logistic.py          perceptron-single-fixed.py
$ **wandb signup
Traceback (most recent call last):
  File "/usr/local/bin/wandb", line 5, in <module>
    from wandb.cli import cli
  File "/usr/local/lib/python3.7/site-packages/wandb/__init__.py", line 45, in <module>
    from wandb.apis import InternalApi, PublicApi, CommError
  File "/usr/local/lib/python3.7/site-packages/wandb/apis/__init__.py", line 97, in <module>
    from .file_stream import FileStreamApi
  File "/usr/local/lib/python3.7/site-packages/wandb/apis/file_stream.py", line 11, in <module>
    from wandb import util
  File "/usr/local/lib/python3.7/site-packages/wandb/util.py", line 24, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'**

>

**Comment by charlesfrye** [comment]
It seems like there's an issue with your Python installation: your `pip install` is affecting Python 2.7, but your `wandb signup` error message indicates it's using Python 3.7.

I would suggest you look around for help getting Python installed.

Also, `wandb signup` was deprecated in favor of `wandb login`. This has been corrected in the video on YouTube.

Good luck!
